version: '3'
services:
  featmap:
    container_name: featmap
    image: amborle/featmap:v1
    restart: always
    networks:
      - projectnet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - './config/conf.json:/opt/featmap/conf.json'
networks:
  projectnet:
    external: true